# Default values for vllm-chart.
replicaCount: 1

image:
  repository: 390888050376.dkr.ecr.us-east-1.amazonaws.com/vllm-server
  pullPolicy: IfNotPresent
  # The tag for the image. By default, it uses the chart's appVersion.
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

# These values are now available for your deployment, but we've hardcoded them
# in the template for now. In a more advanced chart, you'd template these too.
resources:
  limits:
    nvidia.com/gpu: 1
